### ISSUE TITLE
embedding size is not a multiple of 3?

### ISSUE THREAD

**Issue by songweige** [wilson1yan/VideoGPT-Paper#1]
Hi, I'm trying to reproduce the results in the paper but I had some trouble using the pos embedding with provided transformer embedding sizes. The paper use embedding sizes of 1024 and 512, but according to this line https://github.com/wilson1yan/VideoGPT-Paper/blob/f4579d12598889d75cd1946f84faa0e3ab63d945/videogpt/layers/pos_embd.py#L11, the size should be a multiple of n_dim, which is supposed to be 3? Am I missing anything? Thanks!

**Comment by wilson1yan** [comment]
I simplified some of the code and removed some parts related to using multiple codebooks, so there were 4 dimensions in the input to the transformer (T, H, W, # codebooks), hence 512 / 1024. It should work to just choose some multiple of 3 near 512 / 1024 and should produce very similar results.

**Comment by songweige** [comment]
Interesting... I think that makes sense to me. A question irrelevant to the thread but relevant to your response, what is the point to try more than one codebooks other than increase the number of code in the codebook?

**Comment by wilson1yan** [comment]
In general, using multiple codebooks is easier to optimize / less prone to codebook collapse. It also allows more (combinatorially) more expressivity in the codebook with linear scaling in the # of codes when compared to just using 1 codebook.

**Comment by songweige** [comment]
Oh these are good points! Thank you for your patient reply! : )
