### ISSUE TITLE
Reproduce of UCF-101

### ISSUE THREAD

**Issue by kangzhao2** [wilson1yan/VideoGPT-Paper#2]
Hi:

I want to reproduce the results of UCF-101, may I know the total batch size of your experiments? and the corresponding lr? and the total training iterations？

According to your code, I found you don't change the lr when you train the VQ-VAE part?

Kang

**Comment by wilson1yan** [comment]
Hyperparameters for UCF-101 (and all experiments in general) can be found in the appendix of the paper
